[buildPlans.iosevka-term]
family = "Iosevka Term"
spacing = "term"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

  [buildPlans.iosevka-term.variants]
  inherits = "ss20"

    [buildPlans.iosevka-term.variants.design]
    apl-form = 'enable'
    capital-a = "straight-serifless"
    capital-b = "standard-serifless"
    capital-g = "toothless-corner-serifless-hooked"
    capital-j = "serifless"
    capital-k = "symmetric-touching-serifless"
    capital-m = "hanging-serifless"
    capital-q = "crossing"
    capital-r = "straight-serifless"
    capital-v = "straight-serifless"
    capital-w = "straight-serifless"
    capital-x = "straight-serifless"
    capital-y = "straight-serifless"
    capital-z = "straight-serifless"
    a = "double-storey-toothless-corner"
    b = "toothless-corner-serifless"
    d = "toothless-corner-serifless"
    e = "flat-crossbar"
    f = "flat-hook-serifless"
    g = "single-storey-flat-hook-earless-corner"
    j = "serifless"
    k = "symmetric-touching-serifless"
    l = "serifed"
    m = "earless-corner-double-arch-serifless"
    n = "earless-corner-straight-serifless"
    p = "earless-corner-serifless"
    q = "earless-corner-straight-serifless"
    r = "earless-corner-serifless"
    t = "flat-hook-asymmetric"
    u = "toothless-corner-serifless"
    v = "straight-serifless"
    w = "straight-serifless"
    x = "straight-serifless"
    y = "straight-serifless"
    z = "straight-serifless"
    zero = "slashed"
    one = "base"
    two = "straight-neck"
    four = "closed"
    five = "upright-arched"
    six = "straight-bar"
    seven = "straight-serifless"
    eight = "crossing"
    nine = "straight-bar"
    tilde = "low"
    asterisk = "penta-low"
    underscore = "high"
    caret = "low"
    paren = "normal"
    brace = "curly"
    ampersand = "upper-open"
    at = "threefold"
    dollar = "open"
    cent = "open"
    bar = "natural-slope"
    question = "smooth"
    micro-sign = "toothless-corner-serifless"
    lig-neq = "slightly-slanted"
    lig-equal-chain = "without-notch"
    lig-hyphen-chain = "without-notch"

    [buildPlans.iosevka-term.variants.italic]
    capital-z = "cursive"
    e = "rounded"
    f = "flat-hook-tailed"
    k = "diagonal-tailed-cursive-serifless"
    l = "tailed-serifed"
    q = "earless-corner-diagonal-tailed-serifless"
    y = "cursive-flat-hook-serifless"
    z = "cursive"
    two = "curly-neck"
    five = "oblique-flat"
    bar = "force-upright"

  [buildPlans.iosevka-term.ligations]
  inherits = "dlig"

[buildPlans.iosevka-term.weights.Regular]
shape = 300
menu = 400
css = 300

[buildPlans.iosevka-term.weights.Bold]
shape = 600
menu = 700
css = 600

[buildPlans.iosevka-term.widths.Normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.iosevka-term.slopes.Oblique]
angle = 10
shape = "oblique"
menu = "oblique"
css = "oblique"

[buildPlans.iosevka-term.slopes.Italic]
angle = 10
shape = "italic"
menu = "italic"
css = "italic"

[buildPlans.iosevka-term.slopes.Upright]
angle = 0
shape = "upright"
menu  = "upright"
css   = "normal"
