git submodule add https://github.com/w0rp/ale.git ./ale
git submodule add https://github.com/camspiers/animate.vim.git ./animate.vim
git submodule add https://github.com/ayu-theme/ayu-vim.git ./ayu-vim
git submodule add https://github.com/neoclide/coc.nvim.git ./coc.nvim
git submodule add https://github.com/Shougo/deoplete.nvim.git ./deoplete.nvim
git submodule add https://github.com/junegunn/fzf.git ./fzf
git submodule add https://github.com/junegunn/fzf.vim.git ./fzf.vim
git submodule add https://github.com/morhetz/gruvbox.git ./gruvbox
git submodule add https://github.com/joshdick/onedark.vim.git ./helios.vim
git submodule add https://github.com/Yggdroot/indentLine.git ./indentLine
git submodule add https://github.com/vmchale/ion-vim.git ./ion-vim
git submodule add https://github.com/vito-c/jq.vim.git ./jq.vim
git submodule add https://github.com/camspiers/lens.vim.git ./lens.vim
git submodule add https://github.com/itchyny/lightline.vim.git ./lightline.vim
git submodule add https://github.com/leafo/moonscript-vim.git ./moonscript-vim
git submodule add https://github.com/scrooloose/nerdtree.git ./nerdtree
git submodule add https://github.com/Xuyuanp/nerdtree-git-plugin.git ./nerdtree-git-plugin
git submodule add https://github.com/arcticicestudio/nord-vim.git ./nord-vim
git submodule add https://github.com/joshdick/onedark.vim.git ./onedark.vim
git submodule add https://github.com/flrnprz/plastic.vim.git ./plastic.vim
git submodule add https://github.com/powerline/powerline.git ./powerline
git submodule add https://github.com/unblevable/quick-scope.git ./quick-scope
git submodule add https://github.com/vim-scripts/ReplaceWithRegister.git ./ReplaceWithRegister
git submodule add https://github.com/numirias/semshi.git ./semshi
git submodule add https://github.com/godlygeek/tabular.git ./tabular
git submodule add https://github.com/majutsushi/tagbar.git ./tagbar
git submodule add https://github.com/wellle/targets.vim.git ./targets.vim
git submodule add https://github.com/SirVer/ultisnips.git ./ultisnips
git submodule add https://github.com/liuchengxu/vim-clap.git ./vim-clap
git submodule add https://github.com/tpope/vim-commentary.git ./vim-commentary
git submodule add https://github.com/thyrgle/vim-dyon.git ./vim-dyon
git submodule add https://github.com/easymotion/vim-easymotion.git ./vim-easymotion
git submodule add https://github.com/tpope/vim-eunuch.git ./vim-eunuch
git submodule add https://github.com/tommcdo/vim-exchange.git ./vim-exchange
git submodule add https://github.com/rbong/vim-flog.git ./vim-flog
git submodule add https://github.com/tpope/vim-fugitive.git ./vim-fugitive
git submodule add https://github.com/airblade/vim-gitgutter.git ./vim-gitgutter
git submodule add https://github.com/gluon-lang/vim-gluon.git ./vim-gluon
git submodule add https://github.com/machakann/vim-highlightedyank.git ./vim-highlightedyank
git submodule add https://github.com/hylang/vim-hy.git ./vim-hy
git submodule add https://github.com/michaeljsmith/vim-indent-object.git ./vim-indent-object
git submodule add https://github.com/plasticboy/vim-markdown.git ./vim-markdown
git submodule add https://github.com/euclio/vim-markdown-composer.git ./vim-markdown-composer
git submodule add https://github.com/bluz71/vim-nightfly-guicolors.git ./vim-nightfly-guicolors
git submodule add https://github.com/junegunn/vim-peekaboo.git ./vim-peekaboo
git submodule add https://github.com/sheerun/vim-polyglot.git ./vim-polyglot
git submodule add https://github.com/racer-rust/vim-racer.git ./vim-racer
git submodule add https://github.com/machakann/vim-sandwich.git ./vim-sandwich
git submodule add https://github.com/honza/vim-snippets.git ./vim-snippets
git submodule add https://github.com/mhinz/vim-startify.git ./vim-startify
git submodule add https://github.com/lervag/vimtex.git ./vimtex
git submodule add https://github.com/adriaanzon/vim-textobj-matchit.git ./vim-textobj-matchit
git submodule add https://github.com/kana/vim-textobj-user.git ./vim-textobj-user
git submodule add https://github.com/vimwiki/vimwiki.git ./vimwiki
