[username]
show_always = true

[time]
disabled = false
format = "[$time](bold yellow) "

[memory_usage]
disabled = false

[character]
success_symbol = "[\ue0b0](bold green)"
vicmd_symbol = "[\ue0b2](bold green)"

[git_commit]
disabled = false

[rust]
symbol = " "

[env_var]
variable = "SHELL"
style = "dimmed white"
default = "unknown shell"

[custom.nnn]
command = "echo NNN"
when = "test $NNNLVL -gt 0"
description = "nnn level"
