format = "$time$all"

[time]
disabled = false
format = "[$time](bold yellow) "
time_format = "%F %T"

[memory_usage]
disabled = false

[character]
success_symbol = "[\ue0b0](bold green)"
vicmd_symbol = "[\ue0b2](bold green)"

[git_commit]
disabled = false

[rust]
symbol = " "

[shell]
zsh_indicator = "Z"
nu_indicator = "N"
disabled = false

[sudo]
disabled = false

# [custom.nnn]
# command = "echo NNN"
# when = "test $NNNLVL -gt 0"
# description = "nnn level"

[custom.nu-local]
command = 'print "LOCAL"'
when = "exit (if $env.SHELL != ('~/.local/bin/nu' | path expand) { 0 } else { 1 })"
style = "bold purple"
shell = ["nu", "-n", "-c"]
use_stdin = false
description = "local level"
