#!/bin/bash

getsink() {
    sink=$(pactl list short sinks | grep RUN | awk '{print $1}')
    if [ -z "$sink" ]; then
        sink=$(pactl list short sinks | grep -v STOP | awk '{print $1}')
    fi
    echo $sink
}

sink=$(getsink)

case $1 in
    inc)
        pactl -- set-sink-volume $sink +1%
        ;;
    dec)
        pactl -- set-sink-volume $sink -1%
        ;;
    mute)
        pactl set-sink-mute $sink toggle
        ;;
esac
